function model = model_cebra(cebra, args)
    
    % CFG HEADER   
   batch_size = args.batch_size; % default = 512
   learning_rate = args.learning_rate; % default = 1e-4   
   temperature = args.temperature; % default = 0.1
   max_iterations = args.max_iterations; % default = 1000
   max_adapt_iterations = args.max_adapt_iterations; % default = 10
   time_offsets = args.time_offsets; % default = 10
   output_dimension = args.output_dimension; % default = 8
   

   model_architecture = "offset10-model";
   temperature_mode='constant';
   verbose = false;

    %% ---- Convert MATLAB values to Python literals ----
    
    model_architecture = "offset10-model";
    temperature_mode = 'constant';
    verbose = false;
    
    % ---- Create Python CEBRA model ----
    model = py.cebra.CEBRA( ...
        pyargs( ...
            'model_architecture', char(model_architecture), ...
            'device', 'cuda_if_available', ...
            'criterion', 'infonce', ...
            'distance', 'cosine', ...
            'conditional', py.None, ...
            'temperature', temperature, ...
            'temperature_mode', char(temperature_mode), ...
            'min_temperature', 0.1, ...
            'time_offsets', int32(time_offsets), ...
            'delta', py.None, ...
            'max_iterations', int32(max_iterations), ...
            'max_adapt_iterations', int32(max_adapt_iterations), ...
            'batch_size', int32(batch_size), ...
            'learning_rate', learning_rate, ...
            'optimizer', 'adam', ...
            'output_dimension', int32(output_dimension), ...
            'verbose', py.bool(verbose), ...
            'num_hidden_units', int32(32), ...
            'pad_before_transform', py.True, ...
            'hybrid', py.False, ...
            'optimizer_kwargs', py.dict(pyargs( ...
                'betas', py.tuple({0.9, 0.999}), ...
                'eps', 1e-08, ...
                'weight_decay', 0, ...
                'amsgrad', py.False ...
            )) ...
        ) ...
    );
        
end
