function breakoutAxisFields(nexObj, nexPanel, axPtr)
    axFields = fieldnames(axPtr);
    H_panel = nexPanel.ph.Position(4);
    W_panel = nexPanel.ph.Position(3);
    yStep = 25;
    uiHeight = 20;
    m=1;
    H_base = 5;
    for i = 1:length(axFields)
        axField = axFields{i};
        value = axPtr.(axField).value;
        % generate ui spinner
        % Label
        nexPanel.editFields.(axField).Label = uitextarea(nexPanel.ph, ...
            "Value", sprintf("%s", axField), ...
            "Position", [4, H_base + (m+1)*yStep, W_panel*0.95, uiHeight], ...
            "BackgroundColor", [0, 0, 0], ...
            "FontColor", nexObj.nexon.settings.Colors.cyberGreen);

        % Use spinner instead of numeric field
        nexPanel.editFields.(axField).uiField = uispinner(nexPanel.ph, ...
            "Position", [4, H_base + (m+0)*yStep, W_panel*0.8, uiHeight], ...
            "Value", value, ...
            "Step", 1, ...
            "Limits", [-Inf, Inf], ...
            "BackgroundColor", [0, 0, 0], ...
            "ValueChangedFcn", @(src, event) axisPtrChanged(src, event, nexObj, axPtr, axField), ... 
            "FontColor", nexObj.nexon.settings.Colors.cyberGreen);          

        H_base = H_base + uiHeight*2 + 5;
    end
end