function breakoutCfgFieldsV3(nexon, nexObj, nexPanel, cfgParams, entryChangedFcn, entryChangedFcnArgs)
    % VERSION 3 : draw entry panel using spinners instead of numeric edit fields
    entryFields = fieldnames(cfgParams);
    panelSize = nexPanel.ph.Position;
    panelW = panelSize(3);
    panelH = panelSize(4);
    % entryField scalers
    yStepScaler = 25;
    entryHeightScaler = 10;
    
    % Override scalers if specified
    if isfield(entryChangedFcnArgs,"yStepScaler")
        yStepScaler = entryChangedFcnArgs.yStepScaler;
    end
    if isfield(entryChangedFcnArgs,"entryHeightScaler")
        entryHeightScaler = entryChangedFcnArgs.entryHeightScaler;
    end

    m = 1;

    for i = 1:length(entryFields)
        editField = entryFields{i};
        value = cfgParams.(editField);        
        
        % Label
        nexPanel.editFields.(editField).Label = uitextarea(nexPanel.ph, ...
            "Value", sprintf("%s", editField), ...
            "Position", [4, panelH - m*yStepScaler, panelW*0.95, panelH/entryHeightScaler], ...
            "BackgroundColor", [0, 0, 0], ...
            "FontColor", nexon.settings.Colors.cyberGreen);
        
        % UI Control
        switch class(value)
            case "double"
                if isscalar(value)
                    % Use spinner instead of numeric field
                    nexPanel.editFields.(editField).uiField = uispinner(nexPanel.ph, ...
                        "Position", [4, panelH - (m+1)*yStepScaler, panelW*0.8, panelH/entryHeightScaler], ...
                        "Value", value, ...
                        "Step", 0.1, ...
                        "Limits", [-Inf, Inf], ...
                        "BackgroundColor", [0, 0, 0], ...
                        "FontColor", nexon.settings.Colors.cyberGreen);
                else
                    % Use text field for vector/matrix
                    nexPanel.editFields.(editField).uiField = uieditfield(nexPanel.ph, "text", ...
                        "Position", [4, panelH - (m+1)*yStepScaler, panelW*0.8, panelH/entryHeightScaler], ...
                        "Value", array2string(value), ...
                        "BackgroundColor", [0, 0, 0], ...
                        "FontColor", nexon.settings.Colors.cyberGreen);
                end

                nexPanel.editFields.(editField).uiField.ValueChangedFcn = ...
                    @(~,~)entryChangedFcn(nexon, nexObj, nexPanel, editField, entryChangedFcnArgs);

            case "string"
                if isscalar(value)
                    nexPanel.editFields.(editField).uiField = uieditfield(nexPanel.ph, "text", ...
                        "Position", [4, panelH - (m+1)*yStepScaler, panelW*0.8, panelH/entryHeightScaler], ...
                        "Value", char(value), ...
                        "BackgroundColor", [0, 0, 0], ...
                        "FontColor", nexon.settings.Colors.cyberGreen, ...
                        "ValueChangedFcn", @(~,~)entryChangedFcn(nexon, nexObj, nexPanel, editField, entryChangedFcnArgs));
                else
                    nexPanel.editFields.(editField).uiField = uidropdown(nexPanel.ph, ...
                        "Position", [4, panelH - (m+1)*yStepScaler, panelW*0.8, panelH/entryHeightScaler], ...
                        "Value", value(1), ...
                        "Items", cellstr(value), ...
                        "BackgroundColor", nexon.settings.Colors.cyberGreen, ...
                        "FontColor", [0, 0, 0], ...
                        "ValueChangedFcn", @(~,~)entryChangedFcn(nexon, nexObj, nexPanel, editField, entryChangedFcnArgs));
                end
        end
        
        m = m + 2;
    end
end
